postgresql_max_connections: 30     #20 for Prod env
postgresql_wal_level: "hot_standby"
postgresql_hot_standby: "on"
postgresql_statement_timeout: 60000
postgresql_log_lock_waits: "on"
postgresql_log_destination: "csvlog"
postgresql_log_min_duration_statement: 0
postgresql_users:    # Update users for Prod env
  - name: admin
    pass: admin
    encrypted: yes
  - name: service1
    pass: service1
    encrypted: yes
  - name: user1
    pass: user1
    encrypted: yes
  - name: user2
    pass: user2
    encrypted: yes

postgresql_databases:
  - name: db1
    owner: admin